
package utils;

public enum Emoji {

    A("\uD83C\uDD70"),
    Ab("\uD83C\uDD8E"),
    Abc("\uD83D\uDD24"),
    Abcd("\uD83D\uDD21"),
    Accept("\uD83C\uDE51"),
    AerialTramway("\uD83D\uDEA1", Characteristic.Machine),
    Airplane("\u2708", Characteristic.Machine),
    AlarmClock("\u23F0"),
    Alien("\uD83D\uDC7D"),
    Ambulance("\uD83D\uDE91", Characteristic.Machine),
    Anchor("\u2693"),
    Angel("\uD83D\uDC7C", Characteristic.Person),
    Anger("\uD83D\uDCA2", Characteristic.Face),
    Angry("\uD83D\uDE20", Characteristic.Face),
    Anguished("\uD83D\uDE27", Characteristic.Face),
    Ant("\uD83D\uDC1C", Characteristic.Animal),
    Apple("\uD83C\uDF4E", Characteristic.Food, Characteristic.Plant),
    Aquarius("\u2652"),
    Aries("\u2648"),
    ArrowBackward("\u25C0"),
    ArrowDoubleDown("\u23EC"),
    ArrowDoubleUp("\u23EB"),
    ArrowDown("\u2B07"),
    ArrowDownSmall("\uD83D\uDD3D"),
    ArrowForward("\u25B6"),
    ArrowHeadingDown("\u2935"),
    ArrowHeadingUp("\u2934"),
    ArrowLeft("\u2B05"),
    ArrowLowerLeft("\u2199"),
    ArrowLowerRight("\u2198"),
    ArrowRight("\u27A1"),
    ArrowRightHook("\u21AA"),
    ArrowUp("\u2B06"),
    ArrowUpDown("\u2195"),
    ArrowUpSmall("\uD83D\uDD3C"),
    ArrowUpperLeft("\u2196"),
    ArrowUpperRight("\u2197"),
    ArrowsClockwise("\uD83D\uDD03"),
    ArrowsCounterclockwise("\uD83D\uDD04"),
    Art("\uD83C\uDFA8"),
    ArticulatedLorry("\uD83D\uDE9B"),
    Astonished("\uD83D\uDE32", Characteristic.Face),
    AthleticShoe("\uD83D\uDC5F"),
    Atm("\uD83C\uDFE7", Characteristic.Machine),
    B("\uD83C\uDD71"),
    Baby("\uD83D\uDC76", Characteristic.Person),
    BabyBottle("\uD83C\uDF7C"),
    BabyChick("\uD83D\uDC24", Characteristic.Animal),
    BabySymbol("\uD83D\uDEBC"),
    Back("\uD83D\uDD19"),
    BaggageClaim("\uD83D\uDEC4"),
    Balloon("\uD83C\uDF88"),
    BallotBoxWithCheck("\u2611"),
    Bamboo("\uD83C\uDF8D", Characteristic.Plant),
    Banana("\uD83C\uDF4C", Characteristic.Food, Characteristic.Plant),
    BangBang("\u203C"),
    Bank("\uD83C\uDFE6"),
    BarChart("\uD83D\uDCCA"),
    Barber("\uD83D\uDC88"),
    Baseball("\u26BE"),
    Basketball("\uD83C\uDFC0"),
    Bath("\uD83D\uDEC0"),
    Bathtub("\uD83D\uDEC1"),
    Battery("\uD83D\uDD0B"),
    Bear("\uD83D\uDC3B", Characteristic.Animal),
    Bee("\uD83D\uDC1D", Characteristic.Animal),
    Beer("\uD83C\uDF7A", Characteristic.Food),
    Beers("\uD83C\uDF7B", Characteristic.Food),
    Beetle("\uD83D\uDC1E", Characteristic.Animal),
    Beginner("\uD83D\uDD30"),
    Bell("\uD83D\uDD14"),
    Bento("\uD83C\uDF71", Characteristic.Food),
    Bicyclist("\uD83D\uDEB4", Characteristic.Person),
    Bike("\uD83D\uDEB2", Characteristic.Machine),
    Bikini("\uD83D\uDC59"),
    Bird("\uD83D\uDC26", Characteristic.Animal),
    Birthday("\uD83C\uDF82"),
    BlackCircle("\u26AB"),
    BlackJoker("\uD83C\uDCCF"),
    BlackLargeSquare("\u2B1B"),
    BlackMediumSmallSquare("\u25FE"),
    BlackMediumSquare("\u25FC"),
    BlackNib("\u2712"),
    BlackSmallSquare("\u25AA"),
    BlackSquareButton("\uD83D\uDD32"),
    Blossom("\uD83C\uDF3C", Characteristic.Plant),
    Blowfish("\uD83D\uDC21", Characteristic.Animal),
    BlueBook("\uD83D\uDCD8"),
    BlueCar("\uD83D\uDE99"),
    BlueHeart("\uD83D\uDC99"),
    Blush("\uD83D\uDE0A"),
    Boar("\uD83D\uDC17", Characteristic.Animal),
    Bomb("\uD83D\uDCA3"),
    Book("\uD83D\uDCD6"),
    Bookmark("\uD83D\uDD16"),
    BookmarkTabs("\uD83D\uDCD1"),
    Books("\uD83D\uDCDA"),
    Boom("\uD83D\uDCA5"),
    Boot("\uD83D\uDC62"),
    Bouquet("\uD83D\uDC90"),
    Bow("\uD83D\uDE47"),
    Bowling("\uD83C\uDFB3"),
    Boy("\uD83D\uDC66", Characteristic.Person),
    Bread("\uD83C\uDF5E", Characteristic.Food),
    BrideWithVeil("\uD83D\uDC70", Characteristic.Person),
    BridgeAtNight("\uD83C\uDF09"),
    Briefcase("\uD83D\uDCBC"),
    BrokenHeart("\uD83D\uDC94"),
    Bug("\uD83D\uDC1B", Characteristic.Animal),
    Bulb("\uD83D\uDCA1"),
    BulletTrainFront("\uD83D\uDE85", Characteristic.Machine),
    BulletTrainSide("\uD83D\uDE84", Characteristic.Machine),
    Bus("\uD83D\uDE8C", Characteristic.Machine),
    BusStop("\uD83D\uDE8F"),
    BustInSilhouette("\uD83D\uDC64"),
    BustsInSilhouette("\uD83D\uDC65"),
    Cactus("\uD83C\uDF35", Characteristic.Plant),
    Cake("\uD83C\uDF70", Characteristic.Food),
    Calendar("\uD83D\uDCC6"),
    Calling("\uD83D\uDCF2"),
    Camel("\uD83D\uDC2B", Characteristic.Animal),
    Camera("\uD83D\uDCF7", Characteristic.Machine),
    Cancer("\u264B"),
    Candy("\uD83C\uDF6C", Characteristic.Food),
    CapitalAbcd("\uD83D\uDD20"),
    Capricorn("\u2651"),
    CardIndex("\uD83D\uDCC7"),
    CarouselHorse("\uD83C\uDFA0"),
    Cat("\uD83D\uDC31", Characteristic.Animal),
    Cat2("\uD83D\uDC08", Characteristic.Animal),
    Cd("\uD83D\uDCBF"),
    Chart("\uD83D\uDCB9"),
    ChartWithDownwardsTrend("\uD83D\uDCC9"),
    ChartWithUpwardsTrend("\uD83D\uDCC8"),
    CheckeredFlag("\uD83C\uDFC1"),
    Cherries("\uD83C\uDF52", Characteristic.Food, Characteristic.Plant),
    CherryBlossom("\uD83C\uDF38", Characteristic.Plant),
    Chestnut("\uD83C\uDF30", Characteristic.Plant),
    Chicken("\uD83D\uDC14", Characteristic.Animal),
    ChildrenCrossing("\uD83D\uDEB8"),
    ChocolateBar("\uD83C\uDF6B", Characteristic.Food),
    ChristmasTree("\uD83C\uDF84", Characteristic.Plant),
    Church("\u26EA"),
    Cinema("\uD83C\uDFA6"),
    CircusTent("\uD83C\uDFAA"),
    CitySunrise("\uD83C\uDF07"),
    CitySunset("\uD83C\uDF06"),
    Cl("\uD83C\uDD91"),
    Clap("\uD83D\uDC4F"),
    Clapper("\uD83C\uDFAC"),
    Clipboard("\uD83D\uDCCB"),
    Clock1("\uD83D\uDD50"),
    Clock10("\uD83D\uDD59"),
    Clock1030("\uD83D\uDD65"),
    Clock11("\uD83D\uDD5A"),
    Clock1130("\uD83D\uDD66"),
    Clock12("\uD83D\uDD5B"),
    Clock1230("\uD83D\uDD67"),
    Clock130("\uD83D\uDD5C"),
    Clock2("\uD83D\uDD51"),
    Clock230("\uD83D\uDD5D"),
    Clock3("\uD83D\uDD52"),
    Clock330("\uD83D\uDD5E"),
    Clock4("\uD83D\uDD53"),
    Clock430("\uD83D\uDD5F"),
    Clock5("\uD83D\uDD54"),
    Clock530("\uD83D\uDD60"),
    Clock6("\uD83D\uDD55"),
    Clock630("\uD83D\uDD61"),
    Clock7("\uD83D\uDD56"),
    Clock730("\uD83D\uDD62"),
    Clock8("\uD83D\uDD57"),
    Clock830("\uD83D\uDD63"),
    Clock9("\uD83D\uDD58"),
    Clock930("\uD83D\uDD64"),
    ClosedBook("\uD83D\uDCD5"),
    ClosedLockWithKey("\uD83D\uDD10"),
    ClosedUmbrella("\uD83C\uDF02"),
    Cloud("\u2601"),
    Clubs("\u2663"),
    Cn("\uD83C\uDDE8\uD83C\uDDF3"),
    Cocktail("\uD83C\uDF78", Characteristic.Food),
    Coffee("\u2615", Characteristic.Food),
    ColdSweat("\uD83D\uDE30"),
    Computer("\uD83D\uDCBB", Characteristic.Machine),
    ConfettiBall("\uD83C\uDF8A"),
    Confounded("\uD83D\uDE16"),
    Confused("\uD83D\uDE15"),
    Congratulations("\u3297"),
    Construction("\uD83D\uDEA7"),
    ConstructionWorker("\uD83D\uDC77", Characteristic.Person),
    ConvenienceStore("\uD83C\uDFEA"),
    Cookie("\uD83C\uDF6A", Characteristic.Food),
    Cool("\uD83C\uDD92"),
    Cop("\uD83D\uDC6E", Characteristic.Person),
    Copyright("\u00A9"),
    Corn("\uD83C\uDF3D", Characteristic.Food, Characteristic.Plant),
    Couple("\uD83D\uDC6B", Characteristic.Person),
    CoupleKiss("\uD83D\uDC8F", Characteristic.Person),
    CoupleWithHeart("\uD83D\uDC91", Characteristic.Person),
    Cow("\uD83D\uDC2E", Characteristic.Animal),
    Cow2("\uD83D\uDC04", Characteristic.Animal),
    CreditCard("\uD83D\uDCB3"),
    CrescentMoon("\uD83C\uDF19"),
    Crocodile("\uD83D\uDC0A", Characteristic.Animal),
    CrossedFlags("\uD83C\uDF8C"),
    Crown("\uD83D\uDC51"),
    Cry("\uD83D\uDE22", Characteristic.Face),
    CryingCatFace("\uD83D\uDE3F", Characteristic.Face, Characteristic.Animal),
    CrystalBall("\uD83D\uDD2E"),
    Cupid("\uD83D\uDC98"),
    CurlyLoop("\u27B0"),
    CurrencyExchange("\uD83D\uDCB1"),
    Curry("\uD83C\uDF5B", Characteristic.Food),
    Custard("\uD83C\uDF6E", Characteristic.Food),
    Customs("\uD83D\uDEC3"),
    Cyclone("\uD83C\uDF00"),
    Dancer("\uD83D\uDC83", Characteristic.Person),
    Dancers("\uD83D\uDC6F", Characteristic.Person),
    Dango("\uD83C\uDF61"),
    Dart("\uD83C\uDFAF"),
    Dash("\uD83D\uDCA8"),
    Date("\uD83D\uDCC5"),
    De("\uD83C\uDDE9\uD83C\uDDEA"),
    DeciduousTree("\uD83C\uDF33", Characteristic.Plant),
    DepartmentStore("\uD83C\uDFEC"),
    DiamondShapeWithADotInside("\uD83D\uDCA0"),
    Diamonds("\u2666"),
    Disappointed("\uD83D\uDE1E"),
    DisappointedRelieved("\uD83D\uDE25"),
    Dizzy("\uD83D\uDCAB"),
    DizzyFace("\uD83D\uDE35", Characteristic.Face),
    DoNotLitter("\uD83D\uDEAF"),
    Dog("\uD83D\uDC36", Characteristic.Animal),
    Dog2("\uD83D\uDC15", Characteristic.Animal),
    Dollar("\uD83D\uDCB5"),
    Dolls("\uD83C\uDF8E"),
    Dolphin("\uD83D\uDC2C", Characteristic.Animal),
    Door("\uD83D\uDEAA"),
    Doughnut("\uD83C\uDF69", Characteristic.Food),
    Dragon("\uD83D\uDC09", Characteristic.Animal),
    DragonFace("\uD83D\uDC32", Characteristic.Animal, Characteristic.Face),
    Dress("\uD83D\uDC57"),
    DromedaryCamel("\uD83D\uDC2A", Characteristic.Animal),
    Droplet("\uD83D\uDCA7"),
    Dvd("\uD83D\uDCC0"),
    Ear("\uD83D\uDC42"),
    EarOfRice("\uD83C\uDF3E", Characteristic.Food, Characteristic.Plant),
    EarthAfrica("\uD83C\uDF0D"),
    EarthAmericas("\uD83C\uDF0E"),
    EarthAsia("\uD83C\uDF0F"),
    Egg("\uD83C\uDF73", Characteristic.Food),
    Eggplant("\uD83C\uDF46", Characteristic.Food, Characteristic.Plant),
    Eight("\u0038\u20E3"),
    EightBall("\uD83C\uDFB1"),
    EightPointedBlackStar("\u2734"),
    EightSpokedAsterisk("\u2733"),
    ElectricPlug("\uD83D\uDD0C"),
    Elephant("\uD83D\uDC18", Characteristic.Animal),
    Email("\uD83D\uDCE7"),
    End("\uD83D\uDD1A"),
    Envelope("\u2709"),
    EnvelopeWithArrow("\uD83D\uDCE9"),
    Es("\uD83C\uDDEA\uD83C\uDDF8"),
    Euro("\uD83D\uDCB6"),
    EuropeanCastle("\uD83C\uDFF0"),
    EuropeanPostOffice("\uD83C\uDFE4"),
    EvergreenTree("\uD83C\uDF32", Characteristic.Plant),
    Exclamation("\u2757"),
    Expressionless("\uD83D\uDE11", Characteristic.Face),
    Eyeglasses("\uD83D\uDC53"),
    Eyes("\uD83D\uDC40"),
    Factory("\uD83C\uDFED"),
    FallenLeaf("\uD83C\uDF42", Characteristic.Plant),
    Family("\uD83D\uDC6A", Characteristic.Person),
    FastForward("\u23E9"),
    Fax("\uD83D\uDCE0"),
    Fearful("\uD83D\uDE28", Characteristic.Face),
    Feet("\uD83D\uDC3E"),
    FerrisWheel("\uD83C\uDFA1", Characteristic.Machine),
    FileFolder("\uD83D\uDCC1"),
    Fire("\uD83D\uDD25"),
    FireEngine("\uD83D\uDE92", Characteristic.Machine),
    Fireworks("\uD83C\uDF86"),
    FirstQuarterMoon("\uD83C\uDF13"),
    FirstQuarterMoonWithFace("\uD83C\uDF1B"),
    Fish("\uD83D\uDC1F", Characteristic.Animal),
    FishCake("\uD83C\uDF65", Characteristic.Food),
    FishingPoleAndFish("\uD83C\uDFA3"),
    Fist("\u270A"),
    Five("\u0035\u20E3"),
    Flags("\uD83C\uDF8F"),
    Flashlight("\uD83D\uDD26", Characteristic.Machine),
    FloppyDisk("\uD83D\uDCBE", Characteristic.Machine),
    FlowerPlayingCards("\uD83C\uDFB4"),
    Flushed("\uD83D\uDE33", Characteristic.Face),
    Foggy("\uD83C\uDF01"),
    Football("\uD83C\uDFC8"),
    Footprints("\uD83D\uDC63"),
    ForkAndKnife("\uD83C\uDF74"),
    Fountain("\u26F2"),
    Four("\u0034\u20E3"),
    FourLeafClover("\uD83C\uDF40", Characteristic.Plant),
    Fr("\uD83C\uDDEB\uD83C\uDDF7"),
    Free("\uD83C\uDD93"),
    FriedShrimp("\uD83C\uDF64", Characteristic.Food),
    Fries("\uD83C\uDF5F", Characteristic.Food),
    Frog("\uD83D\uDC38", Characteristic.Animal),
    Frowning("\uD83D\uDE26", Characteristic.Face),
    FuelPump("\u26FD", Characteristic.Machine),
    FullMoon("\uD83C\uDF15"),
    FullMoonWithFace("\uD83C\uDF1D"),
    GameDie("\uD83C\uDFB2"),
    Gem("\uD83D\uDC8E"),
    Gemini("\u264A"),
    Ghost("\uD83D\uDC7B"),
    Gift("\uD83C\uDF81"),
    GiftHeart("\uD83D\uDC9D"),
    Girl("\uD83D\uDC67", Characteristic.Person),
    GlobeWithMeridians("\uD83C\uDF10"),
    Goat("\uD83D\uDC10", Characteristic.Animal),
    Golf("\u26F3"),
    Grapes("\uD83C\uDF47", Characteristic.Food, Characteristic.Plant),
    GreenApple("\uD83C\uDF4F", Characteristic.Food, Characteristic.Plant),
    GreenBook("\uD83D\uDCD7"),
    GreenHeart("\uD83D\uDC9A"),
    GreyExclamation("\u2755"),
    GreyQuestion("\u2754"),
    Grimacing("\uD83D\uDE2C", Characteristic.Face),
    Grin("\uD83D\uDE01", Characteristic.Face),
    Grinning("\uD83D\uDE00", Characteristic.Face),
    Guardsman("\uD83D\uDC82", Characteristic.Person),
    Guitar("\uD83C\uDFB8"),
    Gun("\uD83D\uDD2B", Characteristic.Machine),
    Haircut("\uD83D\uDC87"),
    Hamburger("\uD83C\uDF54", Characteristic.Food),
    Hammer("\uD83D\uDD28"),
    Hamster("\uD83D\uDC39", Characteristic.Animal),
    Handbag("\uD83D\uDC5C"),
    Hash("\u0023\u20E3"),
    HatchedChick("\uD83D\uDC25", Characteristic.Animal),
    HatchingChick("\uD83D\uDC23", Characteristic.Animal),
    Headphones("\uD83C\uDFA7"),
    HearNoEvil("\uD83D\uDE49", Characteristic.Animal, Characteristic.Face),
    Heart("\u2764"),
    HeartDecoration("\uD83D\uDC9F"),
    HeartEyes("\uD83D\uDE0D", Characteristic.Face),
    HeartEyesCat("\uD83D\uDE3B", Characteristic.Face, Characteristic.Animal),
    HeartPulse("\uD83D\uDC97"),
    Heartbeat("\uD83D\uDC93"),
    Hearts("\u2665"),
    HeavyCheckMark("\u2714"),
    HeavyDivisionSign("\u2797"),
    HeavyDollarSign("\uD83D\uDCB2"),
    HeavyMinusSign("\u2796"),
    HeavyMultiplicationX("\u2716"),
    HeavyPlusSign("\u2795"),
    Helicopter("\uD83D\uDE81", Characteristic.Machine),
    Herb("\uD83C\uDF3F", Characteristic.Plant),
    Hibiscus("\uD83C\uDF3A", Characteristic.Plant),
    HighBrightness("\uD83D\uDD06"),
    HighHeel("\uD83D\uDC60"),
    HoneyPot("\uD83C\uDF6F", Characteristic.Food),
    Horse("\uD83D\uDC34", Characteristic.Animal),
    HorseRacing("\uD83C\uDFC7"),
    Hospital("\uD83C\uDFE5"),
    HotSprings("\u2668"),
    Hotel("\uD83C\uDFE8"),
    Hourglass("\u231B"),
    HourglassFlowingSand("\u23F3"),
    House("\uD83C\uDFE0"),
    HouseWithGarden("\uD83C\uDFE1"),
    Hushed("\uD83D\uDE2F"),
    IceCream("\uD83C\uDF66", Characteristic.Food),
    IceCreamBowl("\uD83C\uDF68", Characteristic.Food),
    Id("\uD83C\uDD94"),
    IdeographAdvantage("\uD83C\uDE50"),
    Imp("\uD83D\uDC7F"),
    InboxTray("\uD83D\uDCE5"),
    IncomingEnvelope("\uD83D\uDCE8"),
    InformationDeskPerson("\uD83D\uDC81"),
    InformationSource("\u2139"),
    Innocent("\uD83D\uDE07"),
    InterroBang("\u2049"),
    Iphone("\uD83D\uDCF1"),
    It("\uD83C\uDDEE\uD83C\uDDF9"),
    IzakayaLantern("\uD83C\uDFEE"),
    JackOLantern("\uD83C\uDF83", Characteristic.Plant),
    Japan("\uD83D\uDDFE"),
    JapaneseCastle("\uD83C\uDFEF"),
    JapaneseGoblin("\uD83D\uDC7A"),
    JapaneseOgre("\uD83D\uDC79"),
    Jeans("\uD83D\uDC56"),
    Joy("\uD83D\uDE02", Characteristic.Face),
    JoyCat("\uD83D\uDE39", Characteristic.Face, Characteristic.Animal),
    Jp("\uD83C\uDDEF\uD83C\uDDF5"),
    Key("\uD83D\uDD11"),
    KeycapTen("\uD83D\uDD1F"),
    Kimono("\uD83D\uDC58"),
    Kiss("\uD83D\uDC8B"),
    Kissing("\uD83D\uDE17", Characteristic.Face),
    KissingCat("\uD83D\uDE3D", Characteristic.Face, Characteristic.Animal),
    KissingClosedEyes("\uD83D\uDE1A", Characteristic.Face),
    KissingHeart("\uD83D\uDE18", Characteristic.Face),
    KissingSmilingEyes("\uD83D\uDE19", Characteristic.Face),
    Knife("\uD83D\uDD2A"),
    Koala("\uD83D\uDC28", Characteristic.Animal),
    Koko("\uD83C\uDE01"),
    Kr("\uD83C\uDDF0\uD83C\uDDF7"),
    LargeBlueCircle("\uD83D\uDD35"),
    LargeBlueDiamond("\uD83D\uDD37"),
    LargeOrangeDiamond("\uD83D\uDD36"),
    LastQuarterMoon("\uD83C\uDF17"),
    LastQuarterMoonWithFace("\uD83C\uDF1C"),
    Laughing("\uD83D\uDE06", Characteristic.Face),
    Leaves("\uD83C\uDF43", Characteristic.Plant),
    Ledger("\uD83D\uDCD2"),
    LeftLuggage("\uD83D\uDEC5"),
    LeftRightArrow("\u2194"),
    LeftwardsArrowWithHook("\u21A9"),
    Lemon("\uD83C\uDF4B", Characteristic.Food, Characteristic.Plant),
    Leo("\u264C"),
    Leopard("\uD83D\uDC06", Characteristic.Animal),
    Libra("\u264E"),
    LightRail("\uD83D\uDE88", Characteristic.Machine),
    Link("\uD83D\uDD17"),
    Lips("\uD83D\uDC44"),
    Lipstick("\uD83D\uDC84"),
    Lock("\uD83D\uDD12"),
    LockWithInkPen("\uD83D\uDD0F"),
    Lollipop("\uD83C\uDF6D", Characteristic.Food),
    Loop("\u27BF"),
    LoudSound("\uD83D\uDD0A"),
    Loudspeaker("\uD83D\uDCE2"),
    LoveHotel("\uD83C\uDFE9"),
    LoveLetter("\uD83D\uDC8C"),
    LowBrightness("\uD83D\uDD05"),
    M("\u24C2"),
    Mag("\uD83D\uDD0D"),
    MagRight("\uD83D\uDD0E"),
    Mahjong("\uD83C\uDC04"),
    Mailbox("\uD83D\uDCEB"),
    MailboxClosed("\uD83D\uDCEA"),
    MailboxWithMail("\uD83D\uDCEC"),
    MailboxWithNoMail("\uD83D\uDCED"),
    Man("\uD83D\uDC68", Characteristic.Person),
    ManWithGuaPiMao("\uD83D\uDC72", Characteristic.Person),
    ManWithTurban("\uD83D\uDC73", Characteristic.Person),
    MansShoe("\uD83D\uDC5E"),
    MapleLeaf("\uD83C\uDF41", Characteristic.Plant),
    Mask("\uD83D\uDE37"),
    Massage("\uD83D\uDC86"),
    MeatOnBone("\uD83C\uDF56", Characteristic.Food),
    Mega("\uD83D\uDCE3"),
    Melon("\uD83C\uDF48", Characteristic.Food, Characteristic.Plant),
    Mens("\uD83D\uDEB9", Characteristic.Person),
    Metro("\uD83D\uDE87"),
    Microphone("\uD83C\uDFA4", Characteristic.Machine),
    Microscope("\uD83D\uDD2C", Characteristic.Machine),
    MilkyWay("\uD83C\uDF0C"),
    Minibus("\uD83D\uDE90"),
    Minidisc("\uD83D\uDCBD"),
    MobilePhoneOff("\uD83D\uDCF4"),
    MoneyWithWings("\uD83D\uDCB8"),
    Moneybag("\uD83D\uDCB0"),
    Monkey("\uD83D\uDC12", Characteristic.Animal),
    MonkeyFace("\uD83D\uDC35", Characteristic.Animal, Characteristic.Face),
    Monorail("\uD83D\uDE9D", Characteristic.Machine),
    MortarBoard("\uD83C\uDF93"),
    MountFuji("\uD83D\uDDFB"),
    MountainBicyclist("\uD83D\uDEB5", Characteristic.Person),
    MountainCableway("\uD83D\uDEA0"),
    MountainRailway("\uD83D\uDE9E"),
    Mouse("\uD83D\uDC2D", Characteristic.Animal),
    Mouse2("\uD83D\uDC01", Characteristic.Animal),
    MovieCamera("\uD83C\uDFA5"),
    Moyai("\uD83D\uDDFF"),
    Muscle("\uD83D\uDCAA"),
    Mushroom("\uD83C\uDF44", Characteristic.Plant, Characteristic.Food),
    MusicalKeyboard("\uD83C\uDFB9"),
    MusicalNote("\uD83C\uDFB5"),
    MusicalScore("\uD83C\uDFBC"),
    Mute("\uD83D\uDD07"),
    NailCare("\uD83D\uDC85"),
    NameBadge("\uD83D\uDCDB"),
    Necktie("\uD83D\uDC54"),
    NegativeSquaredCrossMark("\u274E"),
    NeutralFace("\uD83D\uDE10"),
    New("\uD83C\uDD95"),
    NewMoon("\uD83C\uDF11"),
    NewMoonWithFace("\uD83C\uDF1A"),
    Newspaper("\uD83D\uDCF0"),
    Ng("\uD83C\uDD96"),
    NightWithStars("\uD83C\uDF03"),
    Nine("\u0039\u20E3"),
    NoBell("\uD83D\uDD15"),
    NoBicycles("\uD83D\uDEB3"),
    NoEntry("\u26D4"),
    NoEntrySign("\uD83D\uDEAB"),
    NoGood("\uD83D\uDE45"),
    NoMobilePhones("\uD83D\uDCF5"),
    NoMouth("\uD83D\uDE36"),
    NoPedestrians("\uD83D\uDEB7"),
    NoSmoking("\uD83D\uDEAD"),
    NonPotableWater("\uD83D\uDEB1"),
    Nose("\uD83D\uDC43"),
    Notebook("\uD83D\uDCD3"),
    NotebookWithDecorativeCover("\uD83D\uDCD4"),
    Notes("\uD83C\uDFB6"),
    NutAndBolt("\uD83D\uDD29"),
    O("\u2B55"),
    O2("\uD83C\uDD7E"),
    Ocean("\uD83C\uDF0A"),
    Octopus("\uD83D\uDC19", Characteristic.Animal),
    Oden("\uD83C\uDF62"),
    Office("\uD83C\uDFE2"),
    Ok("\uD83C\uDD97"),
    OkHand("\uD83D\uDC4C"),
    OkWoman("\uD83D\uDE46"),
    OlderMan("\uD83D\uDC74"),
    OlderWoman("\uD83D\uDC75"),
    On("\uD83D\uDD1B"),
    OncomingAutomobile("\uD83D\uDE98"),
    OncomingBus("\uD83D\uDE8D"),
    OncomingPoliceCar("\uD83D\uDE94"),
    OncomingTaxi("\uD83D\uDE96"),
    One("\u0031\u20E3"),
    OneHundred("\uD83D\uDCAF"),
    OneTwoThreeFour("\uD83D\uDD22"),
    OpenFileFolder("\uD83D\uDCC2"),
    OpenHands("\uD83D\uDC50"),
    OpenMouth("\uD83D\uDE2E"),
    Ophiuchus("\u26CE"),
    OrangeBook("\uD83D\uDCD9"),
    OutboxTray("\uD83D\uDCE4"),
    Ox("\uD83D\uDC02", Characteristic.Animal),
    Package("\uD83D\uDCE6"),
    PageFacingUp("\uD83D\uDCC4"),
    PageWithCurl("\uD83D\uDCC3"),
    Pager("\uD83D\uDCDF"),
    PalmTree("\uD83C\uDF34", Characteristic.Plant),
    PandaFace("\uD83D\uDC3C", Characteristic.Animal, Characteristic.Face),
    Paperclip("\uD83D\uDCCE"),
    Parking("\uD83C\uDD7F"),
    PartAlternationMark("\u303D"),
    PartlySunny("\u26C5"),
    PassportControl("\uD83D\uDEC2"),
    Peach("\uD83C\uDF51", Characteristic.Food, Characteristic.Plant),
    Pear("\uD83C\uDF50", Characteristic.Food, Characteristic.Plant),
    Pencil("\uD83D\uDCDD"),
    Pencil2("\u270F"),
    Penguin("\uD83D\uDC27", Characteristic.Animal),
    Pensive("\uD83D\uDE14", Characteristic.Face),
    PerformingArts("\uD83C\uDFAD"),
    Persevere("\uD83D\uDE23", Characteristic.Face),
    PersonFrowning("\uD83D\uDE4D", Characteristic.Face),
    PersonWithBlondHair("\uD83D\uDC71", Characteristic.Person),
    PersonWithPoutingFace("\uD83D\uDE4E", Characteristic.Person, Characteristic.Face),
    Pig("\uD83D\uDC37", Characteristic.Animal),
    Pig2("\uD83D\uDC16", Characteristic.Animal),
    PigNose("\uD83D\uDC3D"),
    Pill("\uD83D\uDC8A"),
    Pineapple("\uD83C\uDF4D", Characteristic.Food, Characteristic.Plant),
    Pisces("\u2653"),
    Pizza("\uD83C\uDF55", Characteristic.Food),
    PointDown("\uD83D\uDC47"),
    PointLeft("\uD83D\uDC48"),
    PointRight("\uD83D\uDC49"),
    PointUp("\u261D"),
    PointUp2("\uD83D\uDC46"),
    PoliceCar("\uD83D\uDE93"),
    Poodle("\uD83D\uDC29", Characteristic.Animal),
    Poop("\uD83D\uDCA9"),
    PostOffice("\uD83C\uDFE3"),
    PostalHorn("\uD83D\uDCEF"),
    Postbox("\uD83D\uDCEE"),
    PotableWater("\uD83D\uDEB0"),
    Pouch("\uD83D\uDC5D"),
    PoultryLeg("\uD83C\uDF57", Characteristic.Food),
    Pound("\uD83D\uDCB7"),
    PoutingCat("\uD83D\uDE3E", Characteristic.Animal, Characteristic.Face),
    Pray("\uD83D\uDE4F"),
    Princess("\uD83D\uDC78", Characteristic.Person),
    Punch("\uD83D\uDC4A"),
    PurpleHeart("\uD83D\uDC9C"),
    Purse("\uD83D\uDC5B"),
    Pushpin("\uD83D\uDCCC"),
    PutLitterInItsPlace("\uD83D\uDEAE"),
    Question("\u2753"),
    Rabbit("\uD83D\uDC30", Characteristic.Animal),
    Rabbit2("\uD83D\uDC07", Characteristic.Animal),
    Racehorse("\uD83D\uDC0E", Characteristic.Animal),
    Radio("\uD83D\uDCFB", Characteristic.Machine),
    RadioButton("\uD83D\uDD18"),
    Rage("\uD83D\uDE21", Characteristic.Face),
    RailwayCar("\uD83D\uDE83", Characteristic.Machine),
    Rainbow("\uD83C\uDF08"),
    RaisedHand("\u270B"),
    RaisedHands("\uD83D\uDE4C"),
    RaisingHand("\uD83D\uDE4B"),
    Ram("\uD83D\uDC0F", Characteristic.Animal),
    Ramen("\uD83C\uDF5C", Characteristic.Food),
    Rat("\uD83D\uDC00", Characteristic.Animal),
    Recycle("\u267B"),
    RedCar("\uD83D\uDE97"),
    RedCircle("\uD83D\uDD34"),
    Registered("\u00AE"),
    Relaxed("\u263A", Characteristic.Face),
    Relieved("\uD83D\uDE0C", Characteristic.Face),
    Repeat("\uD83D\uDD01"),
    RepeatOne("\uD83D\uDD02"),
    Restroom("\uD83D\uDEBB"),
    RevolvingHearts("\uD83D\uDC9E"),
    Rewind("\u23EA"),
    Ribbon("\uD83C\uDF80"),
    Rice("\uD83C\uDF5A", Characteristic.Food, Characteristic.Plant),
    RiceBall("\uD83C\uDF59", Characteristic.Food),
    RiceCracker("\uD83C\uDF58", Characteristic.Food),
    RiceScene("\uD83C\uDF91"),
    Ring("\uD83D\uDC8D"),
    Rocket("\uD83D\uDE80"),
    RollerCoaster("\uD83C\uDFA2"),
    Rooster("\uD83D\uDC13"),
    Rose("\uD83C\uDF39", Characteristic.Plant),
    RotatingLight("\uD83D\uDEA8"),
    RoundPushpin("\uD83D\uDCCD"),
    Rowboat("\uD83D\uDEA3"),
    Ru("\uD83C\uDDF7\uD83C\uDDFA"),
    RugbyFootball("\uD83C\uDFC9"),
    Runner("\uD83C\uDFC3", Characteristic.Person),
    RunningShirtWithSash("\uD83C\uDFBD", Characteristic.Person),
    Sa("\uD83C\uDE02"),
    Sagittarius("\u2650"),
    Sailboat("\u26F5"),
    Sake("\uD83C\uDF76", Characteristic.Food),
    Sandal("\uD83D\uDC61"),
    Santa("\uD83C\uDF85", Characteristic.Person),
    Satellite("\uD83D\uDCE1", Characteristic.Machine),
    Saxophone("\uD83C\uDFB7"),
    School("\uD83C\uDFEB"),
    SchoolSatchel("\uD83C\uDF92"),
    Scissors("\u2702"),
    Scorpius("\u264F"),
    Scream("\uD83D\uDE31", Characteristic.Face),
    ScreamCat("\uD83D\uDE40", Characteristic.Face, Characteristic.Animal),
    Scroll("\uD83D\uDCDC"),
    Seat("\uD83D\uDCBA"),
    Secret("\u3299"),
    SeeNoEvil("\uD83D\uDE48", Characteristic.Face, Characteristic.Animal),
    Seedling("\uD83C\uDF31", Characteristic.Plant),
    Seven("\u0037\u20E3"),
    ShavedIce("\uD83C\uDF67", Characteristic.Food),
    Sheep("\uD83D\uDC11", Characteristic.Animal),
    Shell("\uD83D\uDC1A"),
    Ship("\uD83D\uDEA2"),
    Shirt("\uD83D\uDC55"),
    Shower("\uD83D\uDEBF"),
    SignalStrength("\uD83D\uDCF6"),
    Six("\u0036\u20E3"),
    SixPointedStar("\uD83D\uDD2F"),
    Ski("\uD83C\uDFBF"),
    Skull("\uD83D\uDC80"),
    Sleeping("\uD83D\uDE34"),
    Sleepy("\uD83D\uDE2A"),
    SlotMachine("\uD83C\uDFB0"),
    SmallBlueDiamond("\uD83D\uDD39"),
    SmallOrangeDiamond("\uD83D\uDD38"),
    SmallRedTriangle("\uD83D\uDD3A"),
    SmallRedTriangleDown("\uD83D\uDD3B"),
    Smile("\uD83D\uDE04", Characteristic.Face),
    SmileCat("\uD83D\uDE38", Characteristic.Face, Characteristic.Animal),
    Smiley("\uD83D\uDE03", Characteristic.Face),
    SmileyCat("\uD83D\uDE3A", Characteristic.Face, Characteristic.Animal),
    SmilingImp("\uD83D\uDE08"),
    Smirk("\uD83D\uDE0F", Characteristic.Face),
    SmirkCat("\uD83D\uDE3C", Characteristic.Face, Characteristic.Animal),
    Smoking("\uD83D\uDEAC"),
    Snail("\uD83D\uDC0C", Characteristic.Animal),
    Snake("\uD83D\uDC0D", Characteristic.Animal),
    Snowboarder("\uD83C\uDFC2", Characteristic.Person),
    Snowflake("\u2744"),
    Snowman("\u26C4"),
    Sob("\uD83D\uDE2D", Characteristic.Face),
    Soccer("\u26BD"),
    Soon("\uD83D\uDD1C"),
    Sos("\uD83C\uDD98"),
    Sound("\uD83D\uDD09"),
    SpaceInvader("\uD83D\uDC7E"),
    Spades("\u2660"),
    Spaghetti("\uD83C\uDF5D", Characteristic.Food),
    Sparkle("\u2747"),
    Sparkler("\uD83C\uDF87"),
    Sparkles("\u2728"),
    SparklingHeart("\uD83D\uDC96"),
    SpeakNoEvil("\uD83D\uDE4A", Characteristic.Face, Characteristic.Animal),
    Speaker("\uD83D\uDD08"),
    SpeechBalloon("\uD83D\uDCAC"),
    Speedboat("\uD83D\uDEA4", Characteristic.Machine),
    Star("\u2B50"),
    Star2("\uD83C\uDF1F"),
    Stars("\uD83C\uDF20"),
    Station("\uD83D\uDE89"),
    StatueOfLiberty("\uD83D\uDDFD"),
    SteamLocomotive("\uD83D\uDE82", Characteristic.Machine),
    Stew("\uD83C\uDF72", Characteristic.Food),
    StraightRuler("\uD83D\uDCCF"),
    Strawberry("\uD83C\uDF53", Characteristic.Food, Characteristic.Plant),
    StuckOutTongue("\uD83D\uDE1B", Characteristic.Face),
    StuckOutTongueClosedEyes("\uD83D\uDE1D", Characteristic.Face),
    StuckOutTongueWinkingEye("\uD83D\uDE1C", Characteristic.Face),
    SunWithFace("\uD83C\uDF1E"),
    Sunflower("\uD83C\uDF3B", Characteristic.Plant),
    Sunglasses("\uD83D\uDE0E"),
    Sunny("\u2600"),
    Sunrise("\uD83C\uDF05"),
    SunriseOverMountains("\uD83C\uDF04"),
    Surfer("\uD83C\uDFC4", Characteristic.Person),
    Sushi("\uD83C\uDF63", Characteristic.Food),
    SuspensionRailway("\uD83D\uDE9F"),
    Sweat("\uD83D\uDE13"),
    SweatDrops("\uD83D\uDCA6"),
    SweatSmile("\uD83D\uDE05", Characteristic.Face),
    SweetPotato("\uD83C\uDF60", Characteristic.Food),
    Swimmer("\uD83C\uDFCA", Characteristic.Person),
    Symbols("\uD83D\uDD23"),
    Syringe("\uD83D\uDC89"),
    Tada("\uD83C\uDF89"),
    TanabataTree("\uD83C\uDF8B", Characteristic.Plant),
    Tangerine("\uD83C\uDF4A", Characteristic.Food, Characteristic.Plant),
    Taurus("\u2649"),
    Taxi("\uD83D\uDE95", Characteristic.Machine),
    Tea("\uD83C\uDF75", Characteristic.Food),
    Telephone("\u260E", Characteristic.Machine),
    TelephoneReceiver("\uD83D\uDCDE"),
    Telescope("\uD83D\uDD2D", Characteristic.Machine),
    Tennis("\uD83C\uDFBE"),
    Tent("\u26FA"),
    ThoughtBalloon("\uD83D\uDCAD"),
    Three("\u0033\u20E3"),
    ThumbsDown("\uD83D\uDC4E"),
    ThumbsUp("\uD83D\uDC4D"),
    Ticket("\uD83C\uDFAB"),
    Tiger("\uD83D\uDC2F", Characteristic.Animal),
    Tiger2("\uD83D\uDC05", Characteristic.Animal),
    TiredFace("\uD83D\uDE2B", Characteristic.Face),
    Tm("\u2122"),
    Toilet("\uD83D\uDEBD"),
    TokyoTower("\uD83D\uDDFC"),
    Tomato("\uD83C\uDF45", Characteristic.Food, Characteristic.Plant),
    Tongue("\uD83D\uDC45"),
    Top("\uD83D\uDD1D"),
    TopHat("\uD83C\uDFA9"),
    Tractor("\uD83D\uDE9C", Characteristic.Machine),
    TrafficLight("\uD83D\uDEA5"),
    Train("\uD83D\uDE8B", Characteristic.Machine),
    Train2("\uD83D\uDE86", Characteristic.Machine),
    Tram("\uD83D\uDE8A", Characteristic.Machine),
    TriangularFlagOnPost("\uD83D\uDEA9"),
    TriangularRuler("\uD83D\uDCD0"),
    Trident("\uD83D\uDD31"),
    Triumph("\uD83D\uDE24", Characteristic.Face),
    Trolleybus("\uD83D\uDE8E", Characteristic.Machine),
    Trophy("\uD83C\uDFC6"),
    TropicalDrink("\uD83C\uDF79", Characteristic.Food),
    TropicalFish("\uD83D\uDC20", Characteristic.Animal),
    Truck("\uD83D\uDE9A", Characteristic.Machine),
    Trumpet("\uD83C\uDFBA"),
    Tulip("\uD83C\uDF37", Characteristic.Plant),
    Turtle("\uD83D\uDC22", Characteristic.Animal),
    Tv("\uD83D\uDCFA", Characteristic.Machine),
    TwistedRightwardsArrows("\uD83D\uDD00"),
    Two("\u0032\u20E3"),
    TwoHearts("\uD83D\uDC95"),
    TwoMenHoldingHands("\uD83D\uDC6C", Characteristic.Person),
    TwoWomenHoldingHands("\uD83D\uDC6D", Characteristic.Person),
    U5272("\uD83C\uDE39"),
    U5408("\uD83C\uDE34"),
    U55B6("\uD83C\uDE3A"),
    U6307("\uD83C\uDE2F"),
    U6708("\uD83C\uDE37"),
    U6709("\uD83C\uDE36"),
    U6E80("\uD83C\uDE35"),
    U7121("\uD83C\uDE1A"),
    U7533("\uD83C\uDE38"),
    U7981("\uD83C\uDE32"),
    U7A7A("\uD83C\uDE33"),
    Uk("\uD83C\uDDEC\uD83C\uDDE7"),
    Umbrella("\u2614"),
    Unamused("\uD83D\uDE12", Characteristic.Face),
    Underage("\uD83D\uDD1E", Characteristic.Face),
    Unlock("\uD83D\uDD13"),
    Up("\uD83C\uDD99"),
    Us("\uD83C\uDDFA\uD83C\uDDF8"),
    V("\u270C"),
    VerticalTrafficLight("\uD83D\uDEA6"),
    Vhs("\uD83D\uDCFC"),
    VibrationMode("\uD83D\uDCF3"),
    VideoCamera("\uD83D\uDCF9"),
    VideoGame("\uD83C\uDFAE"),
    Violin("\uD83C\uDFBB"),
    Virgo("\u264D"),
    Volcano("\uD83C\uDF0B"),
    Vs("\uD83C\uDD9A"),
    Walking("\uD83D\uDEB6"),
    WaningCrescentMoon("\uD83C\uDF18"),
    WaningGibbousMoon("\uD83C\uDF16"),
    Warning("\u26A0"),
    Watch("\u231A"),
    WaterBuffalo("\uD83D\uDC03", Characteristic.Animal),
    Watermelon("\uD83C\uDF49", Characteristic.Food, Characteristic.Plant),
    Wave("\uD83D\uDC4B"),
    WavyDash("\u3030"),
    WaxingCrescentMoon("\uD83C\uDF12"),
    WaxingGibbousMoon("\uD83C\uDF14"),
    Wc("\uD83D\uDEBE"),
    Weary("\uD83D\uDE29", Characteristic.Face),
    Wedding("\uD83D\uDC92"),
    Whale("\uD83D\uDC33", Characteristic.Animal),
    Whale2("\uD83D\uDC0B", Characteristic.Animal),
    Wheelchair("\u267F"),
    WhiteCheckMark("\u2705"),
    WhiteCircle("\u26AA"),
    WhiteFlower("\uD83D\uDCAE", Characteristic.Plant),
    WhiteLargeSquare("\u2B1C"),
    WhiteMediumSmallSquare("\u25FD"),
    WhiteMediumSquare("\u25FB"),
    WhiteSmallSquare("\u25AB"),
    WhiteSquareButton("\uD83D\uDD33"),
    WindChime("\uD83C\uDF90"),
    WineGlass("\uD83C\uDF77"),
    Wink("\uD83D\uDE09", Characteristic.Face),
    Wolf("\uD83D\uDC3A", Characteristic.Animal),
    Woman("\uD83D\uDC69", Characteristic.Person),
    WomansClothes("\uD83D\uDC5A"),
    WomansHat("\uD83D\uDC52"),
    Womens("\uD83D\uDEBA", Characteristic.Person),
    Worried("\uD83D\uDE1F", Characteristic.Face),
    Wrench("\uD83D\uDD27"),
    X("\u274C"),
    YellowHeart("\uD83D\uDC9B"),
    Yen("\uD83D\uDCB4"),
    Yum("\uD83D\uDE0B"),
    Zap("\u26A1"),
    Zero("\u0030\u20E3"),
    Zzz("\uD83D\uDCA4");

    private final String codePoint;

    private final Characteristic[] characteristics;

    private Emoji(String codePoint, Characteristic ... characteristics) {
        this.codePoint = codePoint;
        this.characteristics = characteristics;
    }

    public String getCodePoint() {
        return codePoint;
    }

    public Characteristic[] getCharacteristics() {
        return characteristics;
    }

    @Override public String toString() {
        return codePoint;
    }
}